# Generated by Django 5.2.16 on 2026-09-23 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAutomacaoIxc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login_enderecos', 'Login (Endereços)'), ('atendimentos', 'Atendimentos')], max_length=20, verbose_name='Tipo')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'Processamento 1'), (2, 'Processamento 2')], verbose_name='Grid')),
                ('nome_arquivo_original', models.CharField(max_length=255, verbose_name='Arquivo enviado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=11, verbose_name='Status')),
                ('cancelar_solicitado', models.BooleanField(default=False, verbose_name='Cancelamento solicitado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_automacao_ixc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de automação IXC',
                'verbose_name_plural': 'Execuções de automação IXC',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LinhaExecucaoIxc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linha', models.PositiveIntegerField(verbose_name='Linha na planilha')),
                ('dados_entrada', models.JSONField(verbose_name='Dados da linha')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=8, verbose_name='Status')),
                ('mensagem', models.CharField(blank=True, max_length=500, verbose_name='Mensagem')),
                ('id_ixc', models.CharField(blank=True, max_length=50, verbose_name='ID no IXC')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='ixc.execucaoautomacaoixc')),
            ],
            options={
                'verbose_name': 'Linha de execução IXC',
                'verbose_name_plural': 'Linhas de execução IXC',
                'ordering': ['numero_linha'],
            },
        ),
    ]
