# Generated by Django 5.2.16 on 2026-08-21 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('implantacao_eace', 'Implantação EACE'), ('andamento', 'Andamento'), ('envio_email_faturamento', 'Envio de Email para faturamento'), ('aguardando_financeiro', 'Aguardando financeiro'), ('aguardando_anexo_portal_eace', 'Aguardando Anexo portal EACE'), ('aguardando_validacao_eace', 'Aguardando validação EACE'), ('faturamento_concluido', 'Faturamento Concluído'), ('correcao_mega', 'Correção MEGA')], default='implantacao_eace', max_length=30, verbose_name='Status')),
                ('kit_informado_ixc', models.CharField(blank=True, max_length=100, verbose_name='Kit informado (IXC)')),
                ('divergencia_kit', models.BooleanField(default=False, verbose_name='Divergência de KIT (alerta, RN-002)')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ris', to='escolas.escola', verbose_name='Escola')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ris_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'RI',
                'verbose_name_plural': 'RIs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EmailFinanceiroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('enviado', 'Enviado'), ('recebido', 'Recebido')], max_length=10, verbose_name='Direção')),
                ('remetente', models.EmailField(blank=True, max_length=254, verbose_name='Remetente')),
                ('destinatarios', models.TextField(blank=True, verbose_name='Destinatários')),
                ('assunto', models.CharField(blank=True, max_length=255, verbose_name='Assunto')),
                ('anexo_pdf', models.CharField(blank=True, max_length=500, verbose_name='Anexo PDF (caminho)')),
                ('status_leitura', models.CharField(blank=True, choices=[('ok', 'OK'), ('fora_do_padrao', 'Fora do padrão')], max_length=20, verbose_name='Status de leitura')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_financeiro', to='ri.ri')),
            ],
            options={
                'verbose_name': 'E-mail com o financeiro',
                'verbose_name_plural': 'E-mails com o financeiro',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota_fiscal_pdf', 'Nota Fiscal (PDF)'), ('xml', 'XML')], max_length=20, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='documentos_ri/%Y/%m/', verbose_name='Arquivo')),
                ('versao', models.PositiveIntegerField(default=1, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (versão vigente)')),
                ('recebido_em', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Documento do RI',
                'verbose_name_plural': 'Documentos do RI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RiDivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('valor', 'Divergência de valor'), ('quantidade', 'Divergência de quantidade'), ('kit_relatorio', 'Divergência de KIT (contra relatório)'), ('nf_financeiro', 'Divergência da Nota Fiscal')], max_length=30, verbose_name='Tipo')),
                ('bloqueia', models.BooleanField(default=True, verbose_name='Bloqueia')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Divergência do RI',
                'verbose_name_plural': 'Divergências do RI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RiItemEace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_item', models.CharField(max_length=255, verbose_name='Descrição do item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_eace', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Item do relatório EACE',
                'verbose_name_plural': 'Itens do relatório EACE',
            },
        ),
        migrations.CreateModel(
            name='RiItemIxc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_item', models.CharField(max_length=255, verbose_name='Descrição do item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ixc', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Item do atendimento IXC',
                'verbose_name_plural': 'Itens do atendimento IXC',
            },
        ),
    ]
