# Generated by Django 5.2.16 on 2026-08-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riitemeace',
            options={'verbose_name': 'Item do Kit declarado (1º lado)', 'verbose_name_plural': 'Itens do Kit declarado (1º lado)'},
        ),
        migrations.AlterModelOptions(
            name='riitemixc',
            options={'verbose_name': 'Item do atendimento IXC (2º lado)', 'verbose_name_plural': 'Itens do atendimento IXC (2º lado)'},
        ),
        migrations.CreateModel(
            name='RiItemRelatorioEace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_item', models.CharField(max_length=255, verbose_name='Descrição do item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_relatorio_eace', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Item do Relatório EACE (3º lado)',
                'verbose_name_plural': 'Itens do Relatório EACE (3º lado)',
            },
        ),
    ]
