# Generated by Django 5.2.16 on 2026-08-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0002_alter_riitemeace_options_alter_riitemixc_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensagem', 'Mensagem'), ('anexo', 'Anexo'), ('log_status', 'Mudança de status'), ('log_campo', 'Mudança de campo'), ('email', 'E-mail')], max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('anexo', models.FileField(blank=True, upload_to='ri_historico/%Y/%m/', verbose_name='Anexo')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo alterado')),
                ('valor_anterior', models.CharField(blank=True, max_length=255, verbose_name='Valor anterior')),
                ('valor_novo', models.CharField(blank=True, max_length=255, verbose_name='Valor novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Histórico do RI',
                'verbose_name_plural': 'Histórico do RI',
                'ordering': ['-criado_em'],
            },
        ),
    ]
