# Generated by Django 5.2.16 on 2026-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0003_rihistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri',
            name='dados_financeiro_confirmados_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dados para o financeiro confirmados em'),
        ),
        migrations.AddField(
            model_name='ri',
            name='observacoes_envio_financeiro',
            field=models.TextField(blank=True, verbose_name='Observações para o financeiro'),
        ),
    ]
