# Generated by Django 5.2.16 on 2026-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0004_ri_dados_financeiro_confirmados_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Mesmo texto usado em Escola.kit_inicial (coluna do CONSOLIDADO EACE).', max_length=255, unique=True, verbose_name='Descrição do kit')),
                ('quantidade_padrao', models.PositiveIntegerField(verbose_name='Quantidade padrão')),
                ('valor_unitario_padrao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário padrão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Kit padrão (catálogo de valores)',
                'verbose_name_plural': 'Kits padrão (catálogo de valores)',
                'ordering': ['descricao'],
            },
        ),
    ]
