# Generated by Django 5.2.16 on 2026-08-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0005_kitpadrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitpadrao',
            options={'ordering': ['descricao', 'lote'], 'verbose_name': 'Kit padrão (catálogo de valores)', 'verbose_name_plural': 'Kits padrão (catálogo de valores)'},
        ),
        migrations.RemoveField(
            model_name='kitpadrao',
            name='valor_unitario_padrao',
        ),
        migrations.AddField(
            model_name='kitpadrao',
            name='lote',
            field=models.PositiveIntegerField(blank=True, help_text='Mesmo valor de Escola.lote — o preço varia por lote (ex.: 9, 11).', null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='kitpadrao',
            name='unidade',
            field=models.CharField(blank=True, help_text='Texto da coluna "Unidade" da planilha (Escola, Escola/Mês, Unidade, km, enlace, metro, par). Define se o valor é o KIT fechado da escola ou preço unitário de item avulso.', max_length=50, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='kitpadrao',
            name='valor_equipamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de equipamento'),
        ),
        migrations.AddField(
            model_name='kitpadrao',
            name='valor_servico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de serviço'),
        ),
        migrations.AlterField(
            model_name='kitpadrao',
            name='descricao',
            field=models.CharField(help_text='Mesmo texto usado em Escola.kit_inicial (coluna do CONSOLIDADO EACE).', max_length=255, verbose_name='Descrição do item'),
        ),
        migrations.AlterField(
            model_name='kitpadrao',
            name='quantidade_padrao',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade padrão'),
        ),
        migrations.AddConstraint(
            model_name='kitpadrao',
            constraint=models.UniqueConstraint(fields=('descricao', 'lote'), name='kitpadrao_unico_descricao_lote'),
        ),
    ]
