# Generated by Django 5.2.16 on 2026-08-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0006_alter_kitpadrao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitpadrao',
            name='descricao_curta',
            field=models.CharField(blank=True, help_text='Nome mostrado nas listas do Lado IXC (RN-011) — a Descrição completa é muito longa para um select. Ex.: "Kit Cobertura Wi-Fi - 8 Access Points". Preenchida automaticamente ao salvar quando fica em branco (tira o qualificador entre parênteses do final da Descrição); pode ser digitada à mão para um caso que a regra automática não resolva bem.', max_length=255, verbose_name='Descrição curta'),
        ),
    ]
