# Generated by Django 5.2.16 on 2026-08-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0007_kitpadrao_descricao_curta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ativação'),
        ),
    ]
