# Generated by Django 5.2.16 on 2026-08-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0008_ri_data_ativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitpadrao',
            name='numero_access_points',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de Access Points do kit, extraída automaticamente da Descrição (ex.: "... 4 Access Points" → 4). Usada para cruzar com Escola.kit_inicial quando a EACE informa só o número do KIT, em vez do texto completo (RN-010 ampliada). Fica vazia quando a Descrição não segue esse padrão (itens avulsos: km, enlace, metro, par).', null=True, verbose_name='Número de Access Points'),
        ),
    ]
