# Generated by Django 5.2.16 on 2026-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0011_limpar_parenteses_riitemixc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFinanceiroSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.EmailField(max_length=254, unique=True, verbose_name='Caixa monitorada')),
                ('delta_link', models.TextField(blank=True, verbose_name='Delta link')),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização em')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último erro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sincronização de e-mail do financeiro',
                'verbose_name_plural': 'Sincronizações de e-mail do financeiro',
            },
        ),
        migrations.AddField(
            model_name='emailfinanceirolog',
            name='mensagem_id_externo',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID da mensagem (Graph)'),
        ),
    ]
