# Generated by Django 5.2.16 on 2026-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0012_emailfinanceirosync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri',
            name='estado_ixc',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (Lado IXC, UF)'),
        ),
        migrations.AddField(
            model_name='ri',
            name='municipio_ixc',
            field=models.CharField(blank=True, max_length=150, verbose_name='Município (Lado IXC)'),
        ),
    ]
