# Generated by Django 5.2.16 on 2026-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0013_ri_estado_ixc_ri_municipio_ixc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitpadrao',
            name='aba_planilha_financeiro',
            field=models.CharField(blank=True, help_text='Nome exato da aba na planilha-modelo (ex.: "RACK", "SWITCH", "CONVERSOR"). Não se aplica a KIT (Unidade Escola/Escola-Mês).', max_length=50, verbose_name='Aba da planilha de faturamento'),
        ),
        migrations.AddField(
            model_name='riitemixc',
            name='eh_kit',
            field=models.BooleanField(default=False, verbose_name='É o KIT Instalado (não produto avulso)'),
        ),
    ]
