# Generated by Django 5.2.16 on 2026-08-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0014_kitpadrao_aba_planilha_financeiro_riitemixc_eh_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitpadrao',
            name='aba_planilha_financeiro',
            field=models.CharField(blank=True, help_text='Preencha só para juntar este produto numa aba compartilhada (ex.: "RACK"). Em branco, o produto ganha aba própria, criada automaticamente com o nome dele. Não se aplica a KIT.', max_length=50, verbose_name='Aba da planilha de faturamento (opcional)'),
        ),
    ]
