# Generated by Django 5.2.16 on 2026-08-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0016_alter_ri_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riitemrelatorioeace',
            name='eh_kit',
            field=models.BooleanField(default=False, verbose_name='É o KIT Instalado (não produto avulso)'),
        ),
    ]
