# Generated by Django 5.2.16 on 2026-08-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0017_riitemrelatorioeace_eh_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rihistorico',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='entradas_historico', to='ri.documento', verbose_name='Documentos anexados'),
        ),
    ]
