# Generated by Django 5.2.16 on 2026-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0018_rihistorico_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rihistorico',
            name='mensagem',
            field=models.TextField(blank=True, max_length=250, verbose_name='Mensagem'),
        ),
    ]
