# Generated by Django 5.2.16 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0020_planilhaeace'),
    ]

    operations = [
        migrations.AddField(
            model_name='riitemrelatorioeace',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='riitemrelatorioeace',
            name='num_osp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Num OSP'),
        ),
        migrations.AddField(
            model_name='riitemrelatorioeace',
            name='validacao_osp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Validação OSP'),
        ),
    ]
