# Generated by Django 5.2.16 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0021_riitemrelatorioeace_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riitemrelatorioeace',
            name='status_escola',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status escola'),
        ),
    ]
