# Generated by Django 5.2.16 on 2026-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0023_alter_riitemrelatorioeace_status_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rihistorico',
            name='anexo',
            field=models.FileField(blank=True, max_length=255, upload_to='ri_historico/%Y/%m/', verbose_name='Anexo'),
        ),
    ]
