# Generated by Django 5.2.16 on 2026-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0024_alter_rihistorico_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ (Lado IXC)'),
        ),
        migrations.AddField(
            model_name='ri',
            name='cnpj_ficticio',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ Fictício (Lado IXC)'),
        ),
    ]
