# Generated by Django 5.2.16 on 2026-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0025_ri_cnpj_ri_cnpj_ficticio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ri',
            name='status',
            field=models.CharField(choices=[('implantacao_eace', 'Implantação EACE'), ('andamento', 'Em Andamento'), ('envio_email_faturamento', 'Envio de Email para faturamento'), ('aguardando_financeiro', 'Aguardando financeiro'), ('aguardando_anexo_portal_eace', 'Resposta Financeiro'), ('aguardando_validacao_eace', 'Aguardando validação EACE'), ('faturamento_concluido', 'Faturamento Concluído'), ('correcao_mega', 'Correção MEGA')], default='implantacao_eace', max_length=30, verbose_name='Status'),
        ),
    ]
