# Generated by Django 5.2.16 on 2026-09-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0026_alter_ri_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri',
            name='mes_operacao_ixc',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, verbose_name='Mês da Operação (Lado IXC)'),
        ),
    ]
