# Generated by Django 5.2.16 on 2026-09-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0027_ri_mes_operacao_ixc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRpaEace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=10, verbose_name='Resultado')),
                ('motivo_erro', models.CharField(blank=True, max_length=50, verbose_name='Motivo do erro')),
                ('inep_pdf', models.CharField(blank=True, max_length=20, verbose_name='INEP extraído do PDF')),
                ('produto_pdf', models.CharField(blank=True, max_length=255, verbose_name='Produto extraído do PDF')),
                ('valor_pdf', models.CharField(blank=True, max_length=20, verbose_name='Valor extraído do PDF')),
                ('valor_portal', models.CharField(blank=True, max_length=20, verbose_name='Valor exibido no portal EACE')),
                ('executado_em', models.DateTimeField(blank=True, null=True, verbose_name='Executado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('documento_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_rpa_eace_pdf', to='ri.documento', verbose_name='Nota fiscal (PDF)')),
                ('documento_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_rpa_eace_xml', to='ri.documento', verbose_name='XML')),
                ('ri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_rpa_eace', to='ri.ri')),
            ],
            options={
                'verbose_name': 'Log da RPA EACE',
                'verbose_name_plural': 'Logs da RPA EACE',
                'ordering': ['id'],
            },
        ),
    ]
