# Generated by Django 5.2.16 on 2026-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0028_logrpaeace'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrpaeace',
            name='enfileirado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enfileirado em'),
        ),
        migrations.AddField(
            model_name='logrpaeace',
            name='tentativas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas'),
        ),
        migrations.AlterField(
            model_name='logrpaeace',
            name='resultado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('na_fila', 'Na fila'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=10, verbose_name='Resultado'),
        ),
    ]
