# Generated by Django 5.2.16 on 2026-09-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0029_logrpaeace_enfileirado_em_logrpaeace_tentativas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrpaeace',
            name='resultado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('na_fila', 'Na fila'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=11, verbose_name='Resultado'),
        ),
    ]
