# Generated by Django 5.2.16 on 2026-09-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0030_alter_logrpaeace_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrpaeace',
            name='etapa_atual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etapa atual da RPA'),
        ),
        migrations.AddField(
            model_name='logrpaeace',
            name='progresso_pct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Progresso da RPA (%)'),
        ),
    ]
