# Generated by Django 5.2.16 on 2026-09-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0031_logrpaeace_etapa_atual_logrpaeace_progresso_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='riitemrelatorioeace',
            name='origem_sincronizador',
            field=models.BooleanField(default=False, verbose_name='Lançado/confirmado pelo Sincronizador'),
        ),
    ]
