# Generated by Django 5.2.16 on 2026-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0032_riitemrelatorioeace_origem_sincronizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ri',
            name='pendencias_portal_eace',
            field=models.JSONField(blank=True, default=list, verbose_name='Pendências no portal EACE'),
        ),
        migrations.AddField(
            model_name='ri',
            name='pendencias_portal_eace_consultado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pendências no portal EACE consultadas em'),
        ),
        migrations.AddField(
            model_name='ri',
            name='pendencias_portal_eace_motivo_erro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Motivo do erro na última consulta de pendências'),
        ),
    ]
