# Generated by Django 5.2.16 on 2026-09-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0033_ri_pendencias_portal_eace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrpaeace',
            name='concluido_manualmente',
            field=models.BooleanField(default=False, verbose_name='Concluído manualmente'),
        ),
    ]
