# Generated by Django 5.2.16 on 2026-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0034_logrpaeace_concluido_manualmente'),
    ]

    operations = [
        migrations.AddField(
            model_name='rihistorico',
            name='resultado_validacao_nf',
            field=models.JSONField(blank=True, null=True, verbose_name='Resultado da validação de Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='rihistorico',
            name='tipo',
            field=models.CharField(choices=[('mensagem', 'Mensagem'), ('anexo', 'Anexo'), ('log_status', 'Mudança de status'), ('log_campo', 'Mudança de campo'), ('email', 'E-mail'), ('validacao_nf', 'Validação de Nota Fiscal')], max_length=20, verbose_name='Tipo'),
        ),
    ]
