# Generated by Django 5.2.16 on 2026-09-25 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0035_rihistorico_resultado_validacao_nf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logrpaeace',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='logrpaeace',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='logrpaeace',
            name='criado_manualmente',
            field=models.BooleanField(default=False, verbose_name='Criado manualmente'),
        ),
        migrations.AddField(
            model_name='logrpaeace',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AlterField(
            model_name='logrpaeace',
            name='resultado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('na_fila', 'Na fila'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=11, verbose_name='Resultado'),
        ),
    ]
