# Generated by Django 5.2.16 on 2026-09-26 13:21

from django.db import migrations, models

# Pedido do usuário (2026-09-26; aplicar também nos antigos): INEP no MIP
# fica no RI como "Faturamento RI Concluído". Passam para o novo status:
# - todo RI em "Aguardando validação EACE" ou "Faturamento Concluído";
# - RI atual (mais recente) de todo INEP que já está no MIP;
# - RI parado em "Resposta Financeiro" com a RPA EACE concluída (ao menos
#   1 "Sucesso", nenhum log fora de "Sucesso"/"Cancelado").
# INEP ainda fora do MIP entra nele ("Processo Concluído" quando o RI
# estava em "Faturamento Concluído", "Aguardando Validação EACE" nos
# demais). `update()` direto, sem `Ri.save()` (model histórico).
RESPOSTA_FINANCEIRO = "aguardando_anexo_portal_eace"
AGUARDANDO_VALIDACAO_EACE = "aguardando_validacao_eace"
FATURAMENTO_CONCLUIDO = "faturamento_concluido"
FATURAMENTO_RI_CONCLUIDO = "faturamento_ri_concluido"
ROTULOS = {
    "implantacao_eace": "Implantação EACE",
    "andamento": "Em Andamento",
    "envio_email_faturamento": "Envio de Email para faturamento",
    "aguardando_financeiro": "Aguardando financeiro",
    RESPOSTA_FINANCEIRO: "Resposta Financeiro",
    AGUARDANDO_VALIDACAO_EACE: "Aguardando validação EACE",
    FATURAMENTO_CONCLUIDO: "Faturamento Concluído",
    "correcao_mega": "Correção MEGA",
}


def _rpa_concluida(ri):
    return (
        ri.logs_rpa_eace.filter(resultado="sucesso").exists()
        and not ri.logs_rpa_eace.exclude(resultado__in=("sucesso", "cancelado")).exists()
    )


def migrar_ris_para_faturamento_ri_concluido(apps, schema_editor):
    Ri = apps.get_model("ri", "Ri")
    RiHistorico = apps.get_model("ri", "RiHistorico")
    Escola = apps.get_model("escolas", "Escola")

    ris = {
        ri.pk: ri
        for ri in Ri.objects.filter(status__in=(AGUARDANDO_VALIDACAO_EACE, FATURAMENTO_CONCLUIDO))
    }
    for ri in Ri.objects.filter(status=RESPOSTA_FINANCEIRO):
        if _rpa_concluida(ri):
            ris[ri.pk] = ri
    for escola in Escola.objects.exclude(status_mip__isnull=True).exclude(status_mip=""):
        ri_atual = Ri.objects.filter(escola=escola).order_by("-criado_em").first()
        if ri_atual and ri_atual.status != FATURAMENTO_RI_CONCLUIDO:
            ris[ri_atual.pk] = ri_atual

    Ri.objects.filter(pk__in=ris).update(status=FATURAMENTO_RI_CONCLUIDO)
    RiHistorico.objects.bulk_create(
        RiHistorico(
            ri_id=ri.pk,
            tipo="log_status",
            campo="Status do RI",
            valor_anterior=ROTULOS.get(ri.status, ri.status),
            valor_novo="Faturamento RI Concluído",
        )
        for ri in ris.values()
    )

    fora_do_mip = models.Q(status_mip__isnull=True) | models.Q(status_mip="")
    escolas_concluidas = {ri.escola_id for ri in ris.values() if ri.status == FATURAMENTO_CONCLUIDO}
    Escola.objects.filter(fora_do_mip, pk__in=escolas_concluidas).update(status_mip=FATURAMENTO_CONCLUIDO)
    Escola.objects.filter(fora_do_mip, pk__in={ri.escola_id for ri in ris.values()}).update(
        status_mip=AGUARDANDO_VALIDACAO_EACE
    )


def reverter(apps, schema_editor):
    Ri = apps.get_model("ri", "Ri")
    Ri.objects.filter(status=FATURAMENTO_RI_CONCLUIDO).update(status=AGUARDANDO_VALIDACAO_EACE)


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0036_logrpaeace_cancelamento_e_manual'),
        ('escolas', '0021_rotulo_em_andamento_mip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ri',
            name='status',
            field=models.CharField(choices=[('implantacao_eace', 'Implantação EACE'), ('andamento', 'Em Andamento'), ('envio_email_faturamento', 'Envio de Email para faturamento'), ('aguardando_financeiro', 'Aguardando financeiro'), ('aguardando_anexo_portal_eace', 'Resposta Financeiro'), ('aguardando_validacao_eace', 'Aguardando validação EACE'), ('faturamento_ri_concluido', 'Faturamento RI Concluído'), ('faturamento_concluido', 'Faturamento Concluído'), ('correcao_mega', 'Correção MEGA')], default='implantacao_eace', max_length=30, verbose_name='Status'),
        ),
        migrations.RunPython(migrar_ris_para_faturamento_ri_concluido, reverter),
    ]
