# Generated by Django 5.2.16 on 2026-09-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ri', '0040_implantacao_com_lado3_vai_para_andamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rihistorico',
            name='tipo',
            field=models.CharField(choices=[('mensagem', 'Mensagem'), ('anexo', 'Anexo'), ('log_status', 'Mudança de status'), ('log_campo', 'Mudança de campo'), ('email', 'E-mail'), ('validacao_nf', 'Validação de Nota Fiscal'), ('importacao_massa', 'Importação em massa')], max_length=20, verbose_name='Tipo'),
        ),
    ]
