# Generated by Django 5.2.16 on 2026-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep', models.CharField(max_length=8, unique=True, verbose_name='INEP')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da escola')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('lote', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lote')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(blank=True, max_length=150, verbose_name='Município')),
                ('kit_inicial', models.CharField(blank=True, max_length=100, verbose_name='Kit declarado (EACE)')),
                ('velocidade_dl_minima', models.CharField(blank=True, max_length=50, verbose_name='Velocidade mínima')),
                ('status_conexao', models.CharField(choices=[('desconectado', 'Desconectado'), ('parcialmente_conectado', 'Parcialmente conectado'), ('conectado', 'Conectado')], default='desconectado', max_length=25, verbose_name='Status de conexão')),
                ('data_instalacao_re', models.DateField(blank=True, null=True, verbose_name='Data de instalação RE')),
                ('data_instalacao_ri', models.DateField(blank=True, null=True, verbose_name='Data de instalação RI')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
    ]
