# Generated by Django 5.2.16 on 2026-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='nobreak_inicial',
            field=models.CharField(blank=True, default='Nobreak', help_text='RN-017: item padrão, igual para todas as escolas (sem quantidade/valor, não entra no cálculo financeiro).', max_length=100, verbose_name='Nobreak declarado (EACE)'),
        ),
    ]
