# Generated by Django 5.2.16 on 2026-09-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_planilharelatorioeacemip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaItemRelatorioEaceMip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_item', models.CharField(max_length=255, verbose_name='Descrição do item')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de serviço')),
                ('eh_kit', models.BooleanField(default=False, verbose_name='É o KIT Instalado (não produto avulso)')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=150, verbose_name='Cidade')),
                ('data_emissao_acs', models.DateField(blank=True, null=True, verbose_name='Data Emissão ACS')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_relatorio_eace_mip', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Item do Relatório EACE (MIP, 3º lado)',
                'verbose_name_plural': 'Itens do Relatório EACE (MIP, 3º lado)',
            },
        ),
    ]
