# Generated by Django 5.2.16 on 2026-09-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_escolaitemrelatorioeacemip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilharelatorioeacemip',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='planilharelatorioeacemip',
            name='data_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Data inicial'),
        ),
    ]
