# Generated by Django 5.2.16 on 2026-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_alter_planilharelatorioeacemip_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='encontrado_relatorio_eace_mip',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Encontrado na última sincronização do Relatório EACE (MIP)'),
        ),
    ]
