# Generated by Django 5.2.16 on 2026-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_escola_encontrado_relatorio_eace_mip'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cod_fornecedor',
            field=models.CharField(blank=True, help_text="Coluna 'Cod Fornecedor' da planilha do MIP (RN-069) — igual para toda linha do mesmo INEP; usado junto com o INEP para gerar o arquivo Excel pedido pelo usuário. Gravado pelo Sincronizador do Lado 3, preservado quando o INEP some de uma rodada (mesma regra do `encontrado_relatorio_eace_mip`).", max_length=20, verbose_name='Cód. Fornecedor (Relatório EACE MIP)'),
        ),
    ]
