# Generated by Django 5.2.16 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_escola_cod_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='legado',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente pela importação do histórico do pós-venda — nunca marcado manualmente pela tela.', verbose_name='Dado legado (histórico anterior ao sistema)'),
        ),
    ]
