# Generated by Django 5.2.16 on 2026-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0008_escola_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='status_mip',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento'), ('aguardando_validacao_eace', 'Aguardando Validação EACE'), ('faturamento_concluido', 'Faturamento Concluído')], default=None, help_text="Gravado automaticamente quando o RI chega em 'Aguardando validação EACE' pela 1ª vez (RN-092); editável manualmente só na tela do MIP a partir daí.", max_length=30, null=True, verbose_name='Status (MIP)'),
        ),
    ]
