# Generated by Django 5.2.16 on 2026-09-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0010_backfill_status_mip_faturamento_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='status_mip',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento'), ('aguardando_validacao_eace', 'Aguardando Validação EACE'), ('aguardando_encerramento_lote', 'Aguardando Encerramento LOTE'), ('faturamento_concluido', 'Faturamento Concluído')], default=None, help_text="Gravado automaticamente quando o RI chega em 'Aguardando validação EACE' pela 1ª vez (RN-092); editável manualmente só na tela do MIP a partir daí.", max_length=30, null=True, verbose_name='Status (MIP)'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(max_length=150, verbose_name='Município')),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('escolas', models.ManyToManyField(related_name='lotes', to='escolas.escola', verbose_name='INEPs')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
