# Generated by Django 5.2.16 on 2026-09-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0011_alter_escola_status_mip_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='email_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='lote',
            name='email_enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='E-mail enviado por'),
        ),
    ]
