# Generated by Django 5.2.16 on 2026-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0012_lote_email_enviado_em_lote_email_enviado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('aguardando_encerramento', 'Aguardando Encerramento LOTE'), ('email_enviado', 'Email em LOTE enviado'), ('em_andamento', 'Em Andamento'), ('faturamento_concluido', 'Faturamento Concluído')], default='aguardando_encerramento', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='status_mip',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento'), ('aguardando_validacao_eace', 'Aguardando Validação EACE'), ('aguardando_encerramento_lote', 'Aguardando Encerramento LOTE'), ('email_lote_enviado', 'Email em LOTE enviado'), ('faturamento_concluido', 'Faturamento Concluído')], default=None, help_text="Gravado automaticamente quando o RI chega em 'Aguardando validação EACE' pela 1ª vez (RN-092); editável manualmente só na tela do MIP a partir daí.", max_length=30, null=True, verbose_name='Status (MIP)'),
        ),
    ]
