# Generated by Django 5.2.16 on 2026-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0013_lote_status_alter_escola_status_mip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data início'),
        ),
    ]
