# Generated by Django 5.2.16 on 2026-09-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0014_lote_data_inicio_fim_opcionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='status_mip',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento'), ('aguardando_validacao_eace', 'Aguardando Validação EACE'), ('aguardando_encerramento_lote', 'Aguardando Encerramento LOTE'), ('em_faturamento_lote', 'Em Faturamento'), ('faturamento_concluido', 'Processo Concluído')], default=None, help_text="Gravado automaticamente quando o RI chega em 'Aguardando validação EACE' pela 1ª vez (RN-092); editável manualmente só na tela do MIP a partir daí.", max_length=30, null=True, verbose_name='Status (MIP)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('aguardando_encerramento', 'Aguardando Encerramento LOTE'), ('em_andamento', 'Em Andamento'), ('em_faturamento', 'Em Faturamento'), ('faturamento_concluido', 'Processo Concluído')], default='aguardando_encerramento', max_length=30, verbose_name='Status'),
        ),
    ]
