# Generated by Django 5.2.16 on 2026-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0015_alter_escola_status_mip_alter_lote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilharelatorioeacemip',
            name='sincronizacao_confirmada',
            field=models.BooleanField(default=False, help_text='Marca se o usuário já escolheu sobrepor ou não os INEPs deste arquivo com Lado 3 já preenchido — depois de marcado, a tela para de perguntar de novo até um novo arquivo ser importado.', verbose_name='Sincronização já confirmada'),
        ),
    ]
