# Generated by Django 5.2.16 on 2026-09-17 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0016_planilharelatorioeacemip_sincronizacao_confirmada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='arquivo_notas_fiscais_zip',
            field=models.FileField(blank=True, max_length=255, upload_to='lotes_notas_fiscais/%Y/%m/', verbose_name='Notas Fiscais (.zip)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='nome_original_notas_fiscais_zip',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome original do arquivo de Notas Fiscais'),
        ),
        migrations.AddField(
            model_name='lote',
            name='notas_fiscais_zip_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notas Fiscais (.zip) enviado em'),
        ),
        migrations.AddField(
            model_name='lote',
            name='notas_fiscais_zip_enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Notas Fiscais (.zip) enviado por'),
        ),
    ]
