# Generated by Django 5.2.16 on 2026-09-24 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0017_lote_arquivo_notas_fiscais_zip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasFiscaisMip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='notas_fiscais_mip/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('quantidade_notas_fiscais', models.PositiveIntegerField(verbose_name='Quantidade de Notas Fiscais')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Notas Fiscais (MIP)',
                'verbose_name_plural': 'Notas Fiscais (MIP)',
            },
        ),
    ]
