# Generated by Django 5.2.16 on 2026-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0018_notas_fiscais_mip'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='nota_fiscal_mip',
            field=models.FileField(blank=True, max_length=255, upload_to='notas_fiscais_mip/escolas/%Y/%m/', verbose_name='Nota Fiscal (MIP)'),
        ),
        migrations.AddField(
            model_name='escola',
            name='nota_fiscal_mip_sincronizada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nota Fiscal (MIP) sincronizada em'),
        ),
    ]
