# Generated by Django 5.2.16 on 2026-09-26 14:24

from django.db import migrations, models

# Pedido do usuário (2026-09-26): "Aguardando Encerramento LOTE" saiu —
# LOTE e INEPs nesse status passam para "Em Andamento MIP"; INEP de LOTE
# "Em Andamento" que já recebeu Nota Fiscal (PDF) vai para "Processo
# Concluído". Cada troca do INEP fica no histórico do RI atual.
ROTULOS_MIP = {
    "aguardando_encerramento_lote": "Aguardando Encerramento LOTE",
    "em_andamento": "Em Andamento MIP",
}


def _registrar(RiHistorico, Ri, escola_id, anterior, novo):
    ri = Ri.objects.filter(escola_id=escola_id).order_by("-criado_em").first()
    if ri:
        RiHistorico.objects.create(
            ri=ri, tipo="log_campo", campo="Status (MIP)", valor_anterior=anterior, valor_novo=novo,
        )


def migrar_lotes(apps, schema_editor):
    Escola = apps.get_model("escolas", "Escola")
    Lote = apps.get_model("escolas", "Lote")
    Ri = apps.get_model("ri", "Ri")
    RiHistorico = apps.get_model("ri", "RiHistorico")

    Lote.objects.filter(status="aguardando_encerramento").update(status="em_andamento")
    for escola_id in Escola.objects.filter(status_mip="aguardando_encerramento_lote").values_list("pk", flat=True):
        _registrar(RiHistorico, Ri, escola_id, "Aguardando Encerramento LOTE", "Em Andamento MIP")
    Escola.objects.filter(status_mip="aguardando_encerramento_lote").update(status_mip="em_andamento")

    com_nota = (
        Escola.objects.filter(lotes__status="em_andamento", notas_fiscais_mip__isnull=False)
        .exclude(status_mip="faturamento_concluido")
        .distinct()
    )
    for escola in com_nota:
        _registrar(
            RiHistorico, Ri, escola.pk, ROTULOS_MIP.get(escola.status_mip, escola.status_mip or ""), "Processo Concluído",
        )
    Escola.objects.filter(pk__in=[escola.pk for escola in com_nota]).update(status_mip="faturamento_concluido")



class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0021_rotulo_em_andamento_mip'),
        ('ri', '0040_implantacao_com_lado3_vai_para_andamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='status_mip',
            field=models.CharField(blank=True, choices=[('em_andamento', 'Em Andamento MIP'), ('aguardando_validacao_eace', 'Aguardando Validação EACE'), ('em_faturamento_lote', 'Em Faturamento'), ('faturamento_concluido', 'Processo Concluído')], default=None, help_text="Gravado automaticamente quando o RI chega em 'Aguardando validação EACE' pela 1ª vez (RN-092); editável manualmente só na tela do MIP a partir daí.", max_length=30, null=True, verbose_name='Status (MIP)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento MIP'), ('em_faturamento', 'Em Faturamento'), ('faturamento_concluido', 'Processo Concluído')], default='em_andamento', max_length=30, verbose_name='Status'),
        ),
        migrations.RunPython(migrar_lotes, migrations.RunPython.noop),
    ]
