# Generated by Django 5.2.16 on 2026-09-28 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0022_lote_nasce_em_andamento_mip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacaoNfMip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('na_fila', 'Na fila'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='na_fila', max_length=20, verbose_name='Status')),
                ('origem', models.CharField(choices=[('agendada', 'Agendada'), ('manual', 'Manual')], max_length=20, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('pedido', models.CharField(blank=True, max_length=20, verbose_name='Pedido')),
                ('motivo_erro', models.CharField(blank=True, max_length=255, verbose_name='Motivo do erro')),
                ('etapa_atual', models.CharField(blank=True, max_length=100, verbose_name='Etapa atual')),
                ('progresso_pct', models.PositiveSmallIntegerField(default=0, verbose_name='Progresso (%)')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Validação MIP (NF)',
                'verbose_name_plural': 'Validações MIP (NF)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CardValidacaoNfMip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem no portal')),
                ('municipio', models.CharField(max_length=150, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=10, verbose_name='UF')),
                ('codigo_ibge', models.CharField(blank=True, max_length=10, verbose_name='Cod. IBGE')),
                ('status_portal', models.CharField(max_length=60, verbose_name='Status no portal')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor total a ser emitido')),
                ('validacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='escolas.validacaonfmip', verbose_name='Validação')),
            ],
            options={
                'verbose_name': 'Card da Validação MIP (NF)',
                'verbose_name_plural': 'Cards da Validação MIP (NF)',
                'ordering': ['ordem'],
            },
        ),
    ]
