# Generated by Django 5.2.16 on 2026-09-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0023_validacao_nf_mip'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacaonfmip',
            name='pedido_solicitado',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pedido solicitado'),
        ),
    ]
