# Generated by Django 5.2.16 on 2026-09-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0024_validacao_nf_mip_pedido_solicitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRpaEaceMip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_nota_fiscal', models.CharField(max_length=255, verbose_name='Nome da Nota Fiscal')),
                ('municipio', models.CharField(max_length=150, verbose_name='Município')),
                ('resultado', models.CharField(choices=[('na_fila', 'Na fila'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='na_fila', max_length=11, verbose_name='Resultado')),
                ('motivo_erro', models.CharField(blank=True, max_length=50, verbose_name='Motivo do erro')),
                ('valor_pdf', models.CharField(blank=True, max_length=20, verbose_name='Valor extraído do PDF')),
                ('valor_portal', models.CharField(blank=True, max_length=20, verbose_name='Valor exibido no portal EACE')),
                ('pedido', models.CharField(blank=True, max_length=20, verbose_name='Pedido')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('enfileirado_em', models.DateTimeField(verbose_name='Enfileirado em')),
                ('executado_em', models.DateTimeField(blank=True, null=True, verbose_name='Executado em')),
                ('etapa_atual', models.CharField(blank=True, max_length=100, verbose_name='Etapa atual da RPA')),
                ('progresso_pct', models.PositiveSmallIntegerField(default=0, verbose_name='Progresso da RPA (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_rpa_mip', to='escolas.lote', verbose_name='LOTE')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='escolas.notafiscalmip', verbose_name='Nota Fiscal')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Log da RPA EACE (MIP)',
                'verbose_name_plural': 'Logs da RPA EACE (MIP)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
