# Generated by Django 5.2.16 on 2026-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0025_log_rpa_eace_mip'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrpaeacemip',
            name='status_portal',
            field=models.CharField(blank=True, max_length=60, verbose_name='Status do card no portal EACE'),
        ),
    ]
