# Generated by Django 5.2.16 on 2026-09-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0026_log_rpa_eace_mip_status_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='arquivo_importacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Arquivo da importação em massa'),
        ),
        migrations.AddField(
            model_name='lote',
            name='importado_em_massa',
            field=models.BooleanField(default=False, verbose_name='Criado por importação em massa'),
        ),
    ]
