# Generated by Django 5.2.16 on 2026-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0027_lote_importado_em_massa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='valores_faturados_planilha',
            field=models.JSONField(blank=True, default=dict, verbose_name='Valor faturado por INEP (planilha da importação em massa)'),
        ),
    ]
