# Generated by Django 5.2.16 on 2026-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('alteracao_campo', 'Alteração de campo'), ('transicao_status', 'Transição de status'), ('envio_email', 'Envio de e-mail'), ('recebimento_email', 'Recebimento de e-mail'), ('erro', 'Erro')], max_length=30, verbose_name='Ação')),
                ('entidade', models.CharField(blank=True, max_length=50, verbose_name='Entidade')),
                ('entidade_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID da entidade')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo alterado')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor novo')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
