# Generated by Django 5.2.16 on 2026-09-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='acao',
            field=models.CharField(choices=[('login', 'Login'), ('alteracao_campo', 'Alteração de campo'), ('transicao_status', 'Transição de status'), ('envio_email', 'Envio de e-mail'), ('recebimento_email', 'Recebimento de e-mail'), ('erro', 'Erro'), ('execucao_rpa_eace', 'Execução RPA EACE')], max_length=30, verbose_name='Ação'),
        ),
    ]
